server:
  port: 8082

spring:
  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/user_service_db?currentSchema=public
    username: postgres
    password: password
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  flyway:
    url: jdbc:postgresql://localhost:5432/user_service_db?currentSchema=public
    user: postgres
    password: password
    schemas: public
    locations: classpath:db/migration
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

grpc:
  server:
    port: 50052
  client:
    image-service:
      address: static://localhost:50053
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext


