create table user_roles
(
    id          smallint generated by default as identity
        primary key,
    description varchar(255) not null,
    name        varchar(255) not null
        constraint uk182xa1gitcxqhaq6nn3n2kmo3
            unique
);

alter table user_roles
    owner to postgres;

create index idx_role_name
    on user_roles (name);

create table users
(
    id            uuid         not null
        primary key,
    email         varchar(255) not null
        constraint uk6dotkott2kjsp8vw4d0m25fb7
            unique,
    password_hash varchar(255) not null,
    username      varchar(255) not null
        constraint ukr43af9ap4edm43mmtq01oddj6
            unique
);

alter table users
    owner to postgres;

create table user_profile
(
    user_id             uuid                        not null
        primary key
        constraint fkuganfwvnbll4kn2a3jeyxtyi
            references users,
    image_url            varchar,
    musician_profile_id uuid
        constraint uke06i2imcw5we30ti17lll1x0l
            unique,
    registration_date   timestamp(6) with time zone not null
);

alter table user_profile
    owner to postgres;

create index idx_username
    on users (username);

create index idx_email
    on users (email);

create table users_roles
(
    user_id uuid     not null
        constraint fk2o0jvgh89lemvvo17cbqvdxaa
            references users,
    role_id smallint not null
        constraint fkfivrl5i32jkvd1w39y4h2vn90
            references user_roles,
    primary key (user_id, role_id)
);

alter table users_roles
    owner to postgres;
