server:
  port: 8081

spring:
  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/authentication_service_db?currentSchema=public
    username: postgres
    password: password
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  flyway:
    url: jdbc:postgresql://localhost:5432/authentication_service_db?currentSchema=public
    user: postgres
    password: password
    schemas: public

  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

jwt:
  secret: ${JWT_SECRET:"7FSDJ349DJDV9CAM2M5N593ND3N49DN384ND83N5AQQNFZXC2944CJWHDEJEOA23"}
  access-expiration-ms: ${JWT_ACCESS_EXPIRATION_MS:900000} # 15 минут
  refresh-expiration-ms: ${JWT_ACCESS_EXPIRATION_MS:2592000000} # 1 месяц

grpc:
  server:
    port: 50051
  client:
    user-service:
      address: static://localhost:50052
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext

