server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/authentication_service_db?currentSchema=public
    username: user
    password: password
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  flyway:
    url: jdbc:postgresql://postgres:5432/authentication_service_db?currentSchema=public
    user: user
    password: password
    schemas: public

  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

jwt:
  secret: "7FSDJ349DJDV9CAM2M5N593ND3N49DN384ND83N5AQQNFZXC2944CJWHDEJEOA23"
  access-expiration-ms: 900000 # 15 минут
  refresh-expiration-ms: 2592000000 # 1 месяц

grpc:
  server:
    port: 50051
  client:
    user-service:
      address: static://user-service:8080
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext