server:
  port: 8080

spring:
  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: auth-service-route
          uri: http://localhost:8080
          predicates:
          - Path=/auth/**
        - id: user-service-route
          predicates:
            - Path=/user/**
          uri: http://localhost:8080
          filters:
            - name: JwtValidation

jwt:
  secret: "7FSDJ349DJDV9CAM2M5N593ND3N49DN384ND83N5AQQNFZXC2944CJWHDEJEOA23"
  access-expiration-ms: 900000 # 15 минут

grpc:
  client:
    authentication-service:
      address: static://localhost:50051
      enable-keep-alive: true
      keep-alive-without-calls: true
      negotiation-type: plaintext
