services:
  config-server:
    container_name: config-server
    build:
      context: ../   # -> audio-service-platform
      dockerfile: infrastructure/docker/config-server/Dockerfile
    ports:
      - "${CONFIG_SERVER_PORT:-8888}:${CONFIG_SERVER_PORT:-8888}"
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - CONFIG_SERVER_PORT=${CONFIG_SERVER_PORT}
      - CONFIG_SERVER_SEARCH_LOCATIONS=${CONFIG_SERVER_SEARCH_LOCATIONS}
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCHLOCATIONS=${CONFIG_SERVER_SEARCH_LOCATIONS}
    volumes:
      - ../infrastructure/config/cloud:/config-repo

  api-gateway:
    container_name: api-gateway
    build:
      context: ../
      dockerfile: infrastructure/docker/api-gateway/Dockerfile
    environment:
      - API_GATEWAY_PORT=${API_GATEWAY_PORT}
      - CONFIG_SERVER_URL=${CONFIG_SERVER_URL}
    ports:
      - "${API_GATEWAY_PORT:-8080}:${API_GATEWAY_PORT:-8080}"
    depends_on:
      - config-server


